import rtems_waf.rtems as rtems

def build(bld):
    rtems.build(bld)

    bld(features = 'c cprogram',
        target = 'tsk_set1.exe',
        source = [
            'init.c',
            '../utils.c',
            'tasks.c'
            ]
        )